### ISSUE TITLE
Freq for each core

### ISSUE THREAD

**Issue by diimdeep** [avafinger/htop_2.2.2#3]
Hi, is it possible to display freq for each core with core names like on some screenshots here? https://github.com/avafinger/htop-2.1.1_enhanced-version

**Comment by avafinger** [comment]
I think I removed it because the freq is controlled by the cluster freq, if we have 4 cores in the cluster (LITTLE for example), all cores are at the same freq. for that cluster. Displaying each core freq. it's a waste of space. Maybe x86_64 can have a case for this?

**Comment by diimdeep** [comment]
Got it, thanks.
